apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameoflife
  template:
    metadata:
      labels:
        app: gameoflife
    spec:
      containers:
      - name: app-container
        image: jahnavimanne/gameoflife1
        ports:
          - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: gameoflife
  ports:
  - port: 8080
    targetPort: 8080
